---
# tasks file for apache2

- name: install apache2 
  apt: name=apache2 state=latest

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: deploy html on server
  template: src=index.j2 dest={{ destination_folder }}/index.html mode=0555
  notify:
    - Restart apache2
