---
# tasks file for installnginx
- name: Install nginx
  apt: name=nginx update_cache=yes cache_valid_time=3600

- name: create cert dir
  file: path=/etc/nginx/ssl state=directory

- name: copy TLS key
  copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
  notify: restart nginx
  
- name: copy TLS cert
  copy: src=files/nginx.crt dest={{ cert_file }} 
  notify: restart nginx

- name: copy nginx config file
  template: src=templates/nginx.conf.j2 dest={{ conf_file }}

- name: enable configuration
  file: >
    dest=/etc/nginx/sites-enabled/default
    src={{ conf_file }}
    state=link

- name: copy index.html
  template: src=templates/index.html.j2 dest=/var/www/html/index.html
    mode=0644

- name: restart nginx
  service: name=nginx state=restarted

