---
# tasks file for base-provision


- name: update cache
  apt:
    update_cache: yes

- name: update all packages to the latest version
  apt:
    upgrade: dist


- name: install packages
  apt: name="{{ item }}" state=latest update_cache=yes cache_valid_time=3600
  loop:
    - wget
    - nano
    - mc
    - iperf3
    - net-tools
    - curl
    - git
    - ca-certificates
    - gnupg 


- name: install sublime_text add gpg key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes


- name: add sublimetext repository
  shell: "echo deb https://download.sublimetext.com/ apt/stable/ | sudo tee /etc/apt/sources.list.d/sublime-text.list"

- name: install sublimetext
  apt:
    name: sublime-text
    state: latest
    update_cache: yes



- name: install docker add gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: add repo docker
  shell: "echo deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: install packages docker-ce
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io   


- name: curl docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
  register: result


- name: add execute for docker-compose
  shell: "chmod +x /usr/local/bin/docker-compose"

# - name: take info about intf
#   shell: "uptime"    #"ip link show | cut -f 2 -d ' ' | grep -v '@' | sed -re 's/://g' | egrep '^(enp|eth|eno|ens)'"
#   register: phys_interfaces


# - name: see what in inside
#   debug: var=phys_interfaces	


