---
# tasks file for myenv


- name: update cache
  vars:
    src_file: /home/vadim/Downloads/google-chrome-stable_current_amd64.deb
    dest_file: /home/vadim/Downloads/google-chrome-stable_current_amd64.deb
  apt:
    update_cache: yes
    upgrade: dist

- name: Getting info about system
  shell: "hostnamectl && uptime"
  register: result

- name: install packages list
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - apt-transport-https
    - nano
    - net-tools
    - git
    - ca-certificates
    - curl 
    - gnupg 
    - lsb-release
- debug: msg="{{ result.stdout_lines }}"


- name: add gpg-key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: add repo
  shell: "echo deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: install packages docker-ce
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io   
- debug: msg="{{ result.stdout_lines }}"


- name: curl docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
  register: result
- debug: msg="{{ result }}"


- name: add execute for docker-compose
  shell: "chmod +x /usr/local/bin/docker-compose"

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- name: copy Google.deb
  copy: src={{ src_file }} dest={{ dest_file }}

- name: install Google
  apt: deb=/home/vadim/Downloads/google-chrome-stable_current_amd64.deb
  register: result

- name: Check result
  debug: msg="{{ result }}"