version: '2'
services: 
  nginx:
    image: ansiblebook/nginx-ghost
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - /root/ansible/docker_learn/ghost_box/certs/:/certs
    links:
      - ghost
  ghost:
    image: ghost        
