---

- hosts: all
  gather_facts: no
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  become: yes


- hosts: all
  roles:
    - autho_key
  become: yes
