---

#- hosts: all 
#  gather_facts: yes
#  tasks:
#    - name: install python 3
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
#  become: yes


- hosts: all
  roles:
    - base-provision
  become: yes
