---
- hosts: myhost
  vars_files:
    - ../vars/wordpress.yaml 
  #vars:
  #  paths_to_vars_files:
  #    - vars/wordpress.yml 
  roles:
    - geerlingguy.nginx 
    - geerlingguy.php
    - geerlingguy.mysql
    - wordpress


